language: bash
os:
  - linux"

before_install:
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash -s -- --no-use
  - echo 'export NVM_DIR=$HOME/.nvm' >> $BASH_ENV
  - echo 'source $NVM_DIR/nvm.sh' >> $BASH_ENV
  - nvm install stable

env:
  - BASHVER=
  - BASHVER=3.2
  - BASHVER=4.0
  - BASHVER=4.1
  - BASHVER=4.2
  - BASHVER=4.3
  - BASHVER=4.4

matrix:
  include:
    - os: osx

services:
  - docker

script:
- npm install --only=dev
- |
  if [ "$TRAVIS_OS_NAME" = 'linux' ] && [ -n "$BASHVER" ]; then
    docker build --build-arg bashver=${BASHVER} --tag bats/bats:bash-${BASHVER} .
    docker run -it bash:${BASHVER} --version
    time docker run -it bats/bats:bash-${BASHVER} --tap /opt/bats/test
  else
    time ./node_modules/.bin/bats --tap test
  fi
notifications:
  email:
    on_success: never