language: bash
os:
  - linux

node_js: "stable"

matrix:
  include:
    - os: osx

services:
  - docker

script:
- npm install --only=dev
- time ./node_modules/.bin/bats --tap test
notifications:
  email:
    on_success: never