language: bash
os:
  - linux

env:
  - BASHVER=
  - BASHVER=3.2
  - BASHVER=4.0
  - BASHVER=4.1
  - BASHVER=4.2
  - BASHVER=4.3
  - BASHVER=4.4

node_js: "stable"

matrix:
  include:
    - os: osx
      node_js: "stable"

services:
  - docker

script:
- npm install --only=dev
- |
  if [ "$TRAVIS_OS_NAME" = 'linux' ] && [ -n "$BASHVER" ]; then
    docker build --build-arg bashver=${BASHVER} --tag bats/bats:bash-${BASHVER} .
    docker run -it bash:${BASHVER} --version
    time docker run -it bats/bats:bash-${BASHVER} --tap /opt/bats/test
  else
    time ./node_modules/.bin/bats --tap test
  fi
notifications:
  email:
    on_success: never